CREATE TABLE `feed_loading_sheet` (
  `loading_sheet_id` varchar(36) NOT NULL,
  `loading_sheet_no` varchar(80) NOT NULL,
  `tenant_id` varchar(36) NOT NULL,
  `company_id` varchar(36) NOT NULL,
  `consolidation_id` varchar(36) NOT NULL,
  `consolidation_line_id` varchar(36) NOT NULL,
  `requisition_id` varchar(36) NOT NULL,
  `requisition_line_id` varchar(36) NOT NULL,
  `farm_id` varchar(36) NOT NULL,
  `destination_silo_id` varchar(36),
  `item_id` varchar(36) NOT NULL,
  `mill_loading_bin_id` varchar(36),
  `requested_qty_kg` decimal(14,4) NOT NULL,
  `mill_approved_qty_kg` decimal(14,4) NOT NULL,
  `scheduled_qty_kg` decimal(14,4) NOT NULL,
  `requested_delivery_date` date,
  `production_date` date,
  `compartment_no` varchar(50),
  `kg_loaded` decimal(14,4),
  `loaded_by` varchar(36),
  `loaded_at` timestamp,
  `shipment_id` varchar(36),
  `shipment_no` varchar(80),
  `status` varchar(30) NOT NULL DEFAULT 'DRAFT',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`loading_sheet_id`),
  UNIQUE KEY `feed_loading_sheet_loading_sheet_no_unique` (`loading_sheet_no`),
  UNIQUE KEY `uq_feed_loading_sheet_consolidation_line` (`consolidation_line_id`),
  KEY `idx_feed_loading_sheet_tenant_status` (`tenant_id`,`status`),
  CONSTRAINT `feed_loading_sheet_company_fk` FOREIGN KEY (`company_id`) REFERENCES `company_master` (`company_id`) ON DELETE CASCADE,
  CONSTRAINT `feed_loading_sheet_consolidation_fk` FOREIGN KEY (`consolidation_id`) REFERENCES `feed_consolidation` (`consolidation_id`) ON DELETE CASCADE,
  CONSTRAINT `feed_loading_sheet_consolidation_line_fk` FOREIGN KEY (`consolidation_line_id`) REFERENCES `feed_consolidation_line` (`consolidation_line_id`) ON DELETE CASCADE,
  CONSTRAINT `feed_loading_sheet_requisition_fk` FOREIGN KEY (`requisition_id`) REFERENCES `requisition` (`requisition_id`) ON DELETE RESTRICT,
  CONSTRAINT `feed_loading_sheet_requisition_line_fk` FOREIGN KEY (`requisition_line_id`) REFERENCES `requisition_line` (`line_id`) ON DELETE RESTRICT,
  CONSTRAINT `feed_loading_sheet_farm_fk` FOREIGN KEY (`farm_id`) REFERENCES `location_master` (`location_id`) ON DELETE RESTRICT,
  CONSTRAINT `feed_loading_sheet_silo_fk` FOREIGN KEY (`destination_silo_id`) REFERENCES `location_master` (`location_id`) ON DELETE RESTRICT,
  CONSTRAINT `feed_loading_sheet_item_fk` FOREIGN KEY (`item_id`) REFERENCES `item_master` (`item_id`) ON DELETE RESTRICT,
  CONSTRAINT `feed_loading_sheet_bin_fk` FOREIGN KEY (`mill_loading_bin_id`) REFERENCES `location_master` (`location_id`) ON DELETE RESTRICT
);
