import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsOptional, IsUUID, IsBoolean, IsInt, Min, IsNumber } from 'class-validator';
import { Transform, Type } from 'class-transformer';
import { MasterListQueryDto } from '../../../../common/master-list-query';

export class CreateLocationDto {
  @ApiProperty({ description: 'Company UUID scope', required: false })
  @IsUUID()
  @IsOptional()
  company_id?: string;

  @ApiProperty({ description: 'Nature of Business UUID scope', required: false })
  @IsString()
  @IsOptional()
  nob_id?: string;

  @ApiProperty({ description: 'Line of Business UUID scope', required: false })
  @IsString()
  @IsOptional()
  lob_id?: string;

  /** @deprecated Compatibility input for legacy callers. New records use parent_location_id. */
  @IsUUID()
  @IsOptional()
  farm_id?: string;

  /** @deprecated Compatibility input for legacy callers. New records use parent_location_id. */
  @IsUUID()
  @IsOptional()
  shed_id?: string;

  /** @deprecated Compatibility input for legacy callers. New records use parent_location_id. */
  @IsUUID()
  @IsOptional()
  warehouse_id?: string;

  @ApiProperty({ description: 'Generated by the selected Location Type number series', required: false, readOnly: true })
  @IsString()
  @IsOptional()
  location_code?: string;

  @ApiProperty({ description: 'Full descriptive name of this location', example: 'Storage Area A' })
  @IsString()
  @IsNotEmpty()
  location_name: string;

  @ApiProperty({ description: 'Full postal/physical address shown on batch and reports', example: 'Porta Farm - ABC' })
  @IsString()
  @IsNotEmpty()
  location_address: string;

  @ApiProperty({ description: 'Location Type code from location_type_master', example: 'FARM' })
  @IsString()
  @IsNotEmpty()
  location_type: string;

  @ApiProperty({ description: 'Parent Location UUID', required: false })
  @IsUUID()
  @IsOptional()
  parent_location_id?: string;

  @ApiProperty({ description: 'Size of the physical area', required: false })
  @IsNumber()
  @IsOptional()
  area_size?: number;

  @ApiProperty({ description: 'Unit of area size (e.g. SQFT, SQM)', required: false })
  @IsString()
  @IsOptional()
  area_unit?: string;

  @ApiProperty({ description: 'Maximum storage or bird/animal capacity limit' })
  @IsNumber()
  max_capacity: number;

  @ApiProperty({ description: 'Capacity unit representation' })
  @IsString()
  @IsNotEmpty()
  capacity_uom: string;

  @ApiProperty({ description: 'Current count representation', required: false })
  @IsNumber()
  @IsOptional()
  current_count?: number;

  @ApiProperty({ description: 'GPS coordinates latitude', required: false })
  @IsNumber()
  @IsOptional()
  gps_latitude?: number;

  @ApiProperty({ description: 'GPS coordinates longitude', required: false })
  @IsNumber()
  @IsOptional()
  gps_longitude?: number;

  @ApiProperty({ description: 'Storage conditions type descriptor', required: false })
  @IsString()
  @IsOptional()
  storage_type?: string;

  @ApiProperty({ description: 'Flag indicating if quarantine isolation is enforced', default: false, required: false })
  @IsBoolean()
  @IsOptional()
  is_quarantine_zone?: boolean;

  @ApiProperty({ description: 'Maximum feed capacity of this Silo in KG. Required when location_type = SILO.', required: false })
  @IsNumber()
  @IsOptional()
  @Min(0)
  silo_capacity_kg?: number;

  @ApiProperty({ description: 'Alert when silo stock covers less than this many days of consumption. Required when location_type = SILO.', required: false })
  @IsInt()
  @IsOptional()
  @Min(1)
  silo_reorder_days?: number;

  @ApiProperty({ description: 'Mandatory empty days between batches at this location for biosecurity.', required: false })
  @IsInt()
  @IsOptional()
  @Min(0)
  downtime_days_required?: number;

  @ApiProperty({ description: "The silo or store's own name-number, as the Location Master templates carry it (MGH1, PSL FS - 01, STORE).", required: false })
  @IsString()
  @IsOptional()
  storage_name?: string;

  @ApiProperty({ description: 'Whether feed reaches this location in bags rather than blown into a silo.', required: false })
  @IsBoolean()
  @IsOptional()
  feed_in_bags?: boolean;

  @ApiProperty({ description: 'Flexible custom config configurations in JSON format', required: false })
  @IsOptional()
  extension_config?: any;
}

export class UpdateLocationDto {
  @ApiProperty({ required: false })
  @IsUUID()
  @IsOptional()
  company_id?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  nob_id?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  lob_id?: string;

  /** @deprecated Compatibility input; canonical hierarchy uses parent_location_id. */
  @IsUUID()
  @IsOptional()
  farm_id?: string;

  /** @deprecated Compatibility input; canonical hierarchy uses parent_location_id. */
  @IsUUID()
  @IsOptional()
  shed_id?: string;

  /** @deprecated Compatibility input; canonical hierarchy uses parent_location_id. */
  @IsUUID()
  @IsOptional()
  warehouse_id?: string;

  /** Existing generated codes are immutable; accepted only for old clients and ignored. */
  @IsString()
  @IsOptional()
  location_code?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  location_name?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  location_address?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  location_type?: string;

  @ApiProperty({ required: false })
  @IsUUID()
  @IsOptional()
  parent_location_id?: string;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  area_size?: number;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  area_unit?: string;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  max_capacity?: number;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  capacity_uom?: string;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  current_count?: number;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  gps_latitude?: number;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  gps_longitude?: number;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  storage_type?: string;

  @ApiProperty({ required: false })
  @IsBoolean()
  @IsOptional()
  is_quarantine_zone?: boolean;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  @Min(0)
  silo_capacity_kg?: number;

  @ApiProperty({ required: false })
  @IsInt()
  @IsOptional()
  @Min(1)
  silo_reorder_days?: number;

  @ApiProperty({ required: false })
  @IsInt()
  @IsOptional()
  @Min(0)
  downtime_days_required?: number;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  storage_name?: string;

  @ApiProperty({ required: false })
  @IsBoolean()
  @IsOptional()
  feed_in_bags?: boolean;

  @ApiProperty({ required: false })
  @IsBoolean()
  @IsOptional()
  is_active?: boolean;

  @ApiProperty({ required: false, example: 'ACTIVE', enum: ['ACTIVE', 'INACTIVE', 'ARCHIVE'] })
  @IsString()
  @IsOptional()
  status?: string;

  @ApiProperty({ required: false })
  @IsOptional()
  extension_config?: any;
}

// Extends the shared master list contract, which adds sort, dir and
// filter[column] on top of this master's own named filters. The global
// ValidationPipe runs with forbidNonWhitelisted, so a property that is not
// declared is a 400 rather than an ignored parameter.
export class QueryLocationDto extends MasterListQueryDto {
  @ApiProperty({ description: 'Filter by company UUID', required: false })
  @IsOptional()
  @IsUUID()
  companyId?: string;

  @ApiProperty({ description: 'Filter by Nature of Business UUID', required: false })
  @IsOptional()
  @IsString()
  nobId?: string;

  @ApiProperty({ description: 'Filter by Line of Business UUID', required: false })
  @IsOptional()
  @IsString()
  lobId?: string;

  @ApiProperty({ description: 'Filter by parent farm UUID', required: false })
  @IsOptional()
  @IsUUID()
  farmId?: string;

  @ApiProperty({ description: 'Filter by parent shed UUID', required: false })
  @IsOptional()
  @IsUUID()
  shedId?: string;

  @ApiProperty({ description: 'Filter by linked warehouse UUID', required: false })
  @IsOptional()
  @IsUUID()
  warehouseId?: string;

  @ApiProperty({ description: 'Filter by parent location UUID', required: false })
  @IsOptional()
  @IsUUID()
  parentLocationId?: string;

  @ApiProperty({ description: 'Filter by location type', required: false })
  @IsOptional()
  @IsString()
  locationType?: string;

  @ApiProperty({ description: 'Only locations without a parent', required: false })
  @IsOptional()
  @Transform(({ value }) => value === 'true' ? true : value === 'false' ? false : value)
  @IsBoolean()
  rootOnly?: boolean;

  @ApiProperty({ description: 'Filter by active status', required: false })
  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  isActive?: boolean;

  @ApiProperty({ description: 'Search location code or name', required: false })
  @IsOptional()
  @IsString()
  search?: string;

}
