import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsOptional, IsUUID, IsBoolean, IsInt, Min, Max, IsNumber, ValidateIf, IsIn, IsArray } from 'class-validator';
import { Transform, Type } from 'class-transformer';
import { MasterListQueryDto } from '../../../../common/master-list-query';

export class CreateLocationDto {
  @ApiProperty({ description: 'Company UUID scope', required: false })
  @IsUUID()
  @IsOptional()
  company_id?: string;

  @ApiProperty({ description: 'Nature of Business UUID scope', required: false })
  @IsString()
  @IsOptional()
  nob_id?: string;

  @ApiProperty({ description: 'Line of Business UUID scope', required: false })
  @IsString()
  @IsOptional()
  lob_id?: string;

  /** @deprecated Compatibility input for legacy callers. New records use parent_location_id. */
  @IsUUID()
  @IsOptional()
  farm_id?: string;

  /** @deprecated Compatibility input for legacy callers. New records use parent_location_id. */
  @IsUUID()
  @IsOptional()
  shed_id?: string;

  /** @deprecated Compatibility input for legacy callers. New records use parent_location_id. */
  @IsUUID()
  @IsOptional()
  warehouse_id?: string;

  @ApiProperty({ description: 'Generated by the selected Location Type number series', required: false, readOnly: true })
  @IsString()
  @IsOptional()
  location_code?: string;

  @ApiProperty({ description: 'Full descriptive name of this location', example: 'Storage Area A' })
  @IsString()
  @IsNotEmpty()
  location_name: string;

  @ApiProperty({ description: 'Farm postal/physical address. Required for FARM; omitted for child locations.', required: false })
  @IsString()
  @IsOptional()
  location_address?: string;

  @ApiProperty({ description: 'Location Type code from location_type_master', example: 'FARM' })
  @IsString()
  @IsNotEmpty()
  location_type: string;

  @ApiProperty({ description: 'Parent Location UUID', required: false })
  @IsUUID()
  @IsOptional()
  parent_location_id?: string;

  @ApiProperty({ description: 'Size of the physical area', required: false })
  @IsNumber()
  @IsOptional()
  @Min(0)
  area_size?: number;

  @ApiProperty({ description: 'Unit of area size (e.g. SQFT, SQM)', required: false })
  @IsString()
  @IsOptional()
  area_unit?: string;

  // Not required for SILO: Silo Capacity (KG) + Silo Reorder Days below are
  // what a silo's own capacity/reorder logic actually uses, and asking for a
  // second, general capacity right next to it read as the same question
  // twice (client request, 2026-09-22). ValidateIf keys off the DTO's own
  // location_type field, so this still runs before the entity is loaded.
  @ApiProperty({ description: 'Maximum storage or bird/animal capacity limit. Not required for SILO.', required: false })
  @ValidateIf((dto: CreateLocationDto) => dto.location_type !== 'SILO')
  @IsNumber()
  @Min(0)
  max_capacity?: number;

  @ApiProperty({ description: 'Capacity unit representation. Not required for SILO.', required: false })
  @ValidateIf((dto: CreateLocationDto) => dto.location_type !== 'SILO')
  @IsString()
  @IsNotEmpty()
  capacity_uom?: string;

  @ApiProperty({ description: 'Current count representation', required: false })
  @IsNumber()
  @IsOptional()
  current_count?: number;

  @ApiProperty({ description: 'GPS coordinates latitude', required: false })
  @IsNumber()
  @IsOptional()
  gps_latitude?: number;

  @ApiProperty({ description: 'GPS coordinates longitude', required: false })
  @IsNumber()
  @IsOptional()
  gps_longitude?: number;

  @ApiProperty({ description: 'Storage conditions type descriptor', required: false })
  @IsString()
  @IsOptional()
  storage_type?: string;

  @ApiProperty({ description: 'Flag indicating if quarantine isolation is enforced', default: false, required: false })
  @IsBoolean()
  @IsOptional()
  is_quarantine_zone?: boolean;

  @ApiProperty({ description: 'Maximum feed capacity of this Silo in KG. Required when location_type = SILO.', required: false })
  @IsNumber()
  @IsOptional()
  @Min(0)
  silo_capacity_kg?: number;

  // The number the client types is not necessarily the number stored. Silo
  // capacity is quoted in tonnes as often as in kilogrammes, and a farm that
  // enters 40 meaning 40 TON against a column documented as KG is a
  // thousandfold error nothing downstream could detect. So the unit travels
  // with the figure and the service converts on write; silo_capacity_kg stays
  // canonical kilogrammes in the database whichever unit was chosen.
  @ApiProperty({ description: "Unit the silo capacity above was entered in. TON is multiplied by 1000 on write. Required when location_type = SILO.", required: false, enum: ['KG', 'TON'] })
  @IsIn(['KG', 'TON'])
  @IsOptional()
  silo_capacity_uom?: 'KG' | 'TON';

  // Not a column. The sheds a silo feeds are recorded in silo_shed_link
  // (spec D7), a many-to-many table: one silo serves many sheds, and — unlike
  // the old feed_silo_id column this replaced — a shed may now draw from
  // several silos too, one per feed item. The silo form still wants to edit
  // the set from the silo's side, so this array is a view over that table —
  // the service links every shed listed here and unlinks any shed dropped
  // from the list.
  @ApiProperty({ description: 'SHED location UUIDs this Silo feeds via silo_shed_link. A shed may draw from several silos, one per feed item; sheds dropped from the list are unlinked.', required: false, type: [String] })
  @IsOptional()
  @IsArray()
  @IsUUID('4', { each: true })
  attached_sheds?: string[];

  @ApiProperty({ description: 'Alert when silo stock covers less than this many days of consumption. Required when location_type = SILO.', required: false })
  @IsInt()
  @IsOptional()
  @Min(1)
  silo_reorder_days?: number;

  @ApiProperty({ description: 'Mandatory empty days between batches at this location for biosecurity.', required: false })
  @IsInt()
  @IsOptional()
  @Min(0)
  downtime_days_required?: number;

  @ApiProperty({ description: "The silo or store's own name-number, as the Location Master templates carry it (MGH1, PSL FS - 01, STORE).", required: false })
  @IsString()
  @IsOptional()
  storage_name?: string;

  // Spec D3: Feed Forecast's refill date is run-down minus this many days.
  // Per farm because delivery distance is per farm; applies to FARM rows.
  @ApiProperty({ description: 'Feed Forecast: the refill date is this many days before a silo runs out. Applies to FARM.', required: false })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(30)
  feed_refill_buffer_days?: number;

  // Spec D19: Required On = Date to Refill - this many days; default 2.
  @ApiProperty({ description: 'Feed Forecast: Required On is this many days before the Date to Refill (spec D19, default 2). Applies to FARM.', required: false })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(30)
  feed_lead_time_days?: number;

  // Master Setup §1 row 10: low feed alert at or below this System Balance.
  @ApiProperty({ description: 'SILO: low feed alert when System Balance is at or below this many KG. Blank = no low alert.', required: false, nullable: true })
  @IsOptional()
  @IsNumber()
  @Min(0)
  low_level_kg?: number | null;

  // Master Setup §1 row 12: over-stock notice at or above this System Balance.
  @ApiProperty({ description: 'SILO: over-stock notice when System Balance is at or above this many KG (typically 90% of capacity). Blank = none.', required: false, nullable: true })
  @IsOptional()
  @IsNumber()
  @Min(0)
  high_level_kg?: number | null;

  @ApiProperty({ description: 'FARM: bulk feed orders round up to this many kilograms (Requisition §1 row 28, default 3000).', required: false })
  @IsOptional()
  @IsInt()
  @Min(1)
  feed_bulk_multiple_kg?: number;

  @ApiProperty({ description: 'FARM: bagged feed rounds to whole bags of this many kilograms (checkpoint 27, default 50).', required: false })
  @IsOptional()
  @IsInt()
  @Min(1)
  feed_bag_size_kg?: number;

  @ApiProperty({ description: 'FARM: normal bulk truck load in KG — a planning target, not a cap (Requisition §1 row 27, default 30000).', required: false })
  @IsOptional()
  @IsInt()
  @Min(1)
  feed_truck_target_kg?: number;

  @ApiProperty({ description: 'FARM: weekday feed is produced for this farm, 0 = Sunday … 6 = Saturday. The requisition deadline is the day before (default Sunday, so Saturday).', required: false })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(6)
  feed_production_weekday?: number;

  @ApiProperty({ description: 'Flexible custom config configurations in JSON format', required: false })
  @IsOptional()
  extension_config?: any;
}

export class UpdateLocationDto {
  @ApiProperty({ required: false })
  @IsUUID()
  @IsOptional()
  company_id?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  nob_id?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  lob_id?: string;

  /** @deprecated Compatibility input; canonical hierarchy uses parent_location_id. */
  @IsUUID()
  @IsOptional()
  farm_id?: string;

  /** @deprecated Compatibility input; canonical hierarchy uses parent_location_id. */
  @IsUUID()
  @IsOptional()
  shed_id?: string;

  /** @deprecated Compatibility input; canonical hierarchy uses parent_location_id. */
  @IsUUID()
  @IsOptional()
  warehouse_id?: string;

  /** Existing generated codes are immutable; accepted only for old clients and ignored. */
  @IsString()
  @IsOptional()
  location_code?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  location_name?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  location_address?: string;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  location_type?: string;

  @ApiProperty({ required: false })
  @IsUUID()
  @IsOptional()
  parent_location_id?: string;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  @Min(0)
  area_size?: number;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  area_unit?: string;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  @Min(0)
  max_capacity?: number;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  capacity_uom?: string;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  current_count?: number;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  gps_latitude?: number;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  gps_longitude?: number;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  storage_type?: string;

  @ApiProperty({ required: false })
  @IsBoolean()
  @IsOptional()
  is_quarantine_zone?: boolean;

  @ApiProperty({ required: false })
  @IsNumber()
  @IsOptional()
  @Min(0)
  silo_capacity_kg?: number;

  @ApiProperty({ required: false, enum: ['KG', 'TON'] })
  @IsIn(['KG', 'TON'])
  @IsOptional()
  silo_capacity_uom?: 'KG' | 'TON';

  // A view over silo_shed_link, not a column here; see the create DTO for why
  // the set lives in that table rather than on either row.
  @ApiProperty({ description: 'SHED location UUIDs this Silo feeds via silo_shed_link. Sheds dropped from the list are unlinked.', required: false, type: [String] })
  @IsOptional()
  @IsArray()
  @IsUUID('4', { each: true })
  attached_sheds?: string[];

  @ApiProperty({ required: false })
  @IsInt()
  @IsOptional()
  @Min(1)
  silo_reorder_days?: number;

  @ApiProperty({ required: false })
  @IsInt()
  @IsOptional()
  @Min(0)
  downtime_days_required?: number;

  @ApiProperty({ required: false })
  @IsString()
  @IsOptional()
  storage_name?: string;

  @ApiProperty({ description: 'Feed Forecast: the refill date is this many days before a silo runs out. Applies to FARM.', required: false })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(30)
  feed_refill_buffer_days?: number;

  // Spec D19: Required On = Date to Refill - this many days; default 2.
  @ApiProperty({ description: 'Feed Forecast: Required On is this many days before the Date to Refill (spec D19, default 2). Applies to FARM.', required: false })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(30)
  feed_lead_time_days?: number;

  // Master Setup §1 row 10: low feed alert at or below this System Balance.
  @ApiProperty({ description: 'SILO: low feed alert when System Balance is at or below this many KG. Blank = no low alert.', required: false, nullable: true })
  @IsOptional()
  @IsNumber()
  @Min(0)
  low_level_kg?: number | null;

  // Master Setup §1 row 12: over-stock notice at or above this System Balance.
  @ApiProperty({ description: 'SILO: over-stock notice when System Balance is at or above this many KG (typically 90% of capacity). Blank = none.', required: false, nullable: true })
  @IsOptional()
  @IsNumber()
  @Min(0)
  high_level_kg?: number | null;

  @ApiProperty({ description: 'FARM: bulk feed orders round up to this many kilograms (Requisition §1 row 28, default 3000).', required: false })
  @IsOptional()
  @IsInt()
  @Min(1)
  feed_bulk_multiple_kg?: number;

  @ApiProperty({ description: 'FARM: bagged feed rounds to whole bags of this many kilograms (checkpoint 27, default 50).', required: false })
  @IsOptional()
  @IsInt()
  @Min(1)
  feed_bag_size_kg?: number;

  @ApiProperty({ description: 'FARM: normal bulk truck load in KG — a planning target, not a cap (Requisition §1 row 27, default 30000).', required: false })
  @IsOptional()
  @IsInt()
  @Min(1)
  feed_truck_target_kg?: number;

  @ApiProperty({ description: 'FARM: weekday feed is produced for this farm, 0 = Sunday … 6 = Saturday. The requisition deadline is the day before (default Sunday, so Saturday).', required: false })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(6)
  feed_production_weekday?: number;

  @ApiProperty({ required: false })
  @IsBoolean()
  @IsOptional()
  is_active?: boolean;

  @ApiProperty({ required: false, example: 'ACTIVE', enum: ['ACTIVE', 'INACTIVE', 'ARCHIVE'] })
  @IsString()
  @IsOptional()
  status?: string;

  @ApiProperty({ required: false })
  @IsOptional()
  extension_config?: any;
}

// Extends the shared master list contract, which adds sort, dir and
// filter[column] on top of this master's own named filters. The global
// ValidationPipe runs with forbidNonWhitelisted, so a property that is not
// declared is a 400 rather than an ignored parameter.
export class QueryLocationDto extends MasterListQueryDto {
  @ApiProperty({ description: 'Filter by company UUID', required: false })
  @IsOptional()
  @IsUUID()
  companyId?: string;

  @ApiProperty({ description: 'Filter by Nature of Business UUID', required: false })
  @IsOptional()
  @IsString()
  nobId?: string;

  @ApiProperty({ description: 'Filter by Line of Business UUID', required: false })
  @IsOptional()
  @IsString()
  lobId?: string;

  @ApiProperty({ description: 'Filter by parent farm UUID', required: false })
  @IsOptional()
  @IsUUID()
  farmId?: string;

  @ApiProperty({ description: 'Filter by parent shed UUID', required: false })
  @IsOptional()
  @IsUUID()
  shedId?: string;

  @ApiProperty({ description: 'Filter by linked warehouse UUID', required: false })
  @IsOptional()
  @IsUUID()
  warehouseId?: string;

  @ApiProperty({ description: 'Filter by parent location UUID', required: false })
  @IsOptional()
  @IsUUID()
  parentLocationId?: string;

  @ApiProperty({ description: 'Filter by location type', required: false })
  @IsOptional()
  @IsString()
  locationType?: string;

  @ApiProperty({
    description: 'Only locations that may be the parent of a new location of this type — those whose type is in that '
      + "Location Type's allowed_parent_types. A root type (empty list) returns no rows.",
    required: false,
    example: 'SHED',
  })
  @IsOptional()
  @IsString()
  parentForType?: string;

  // The Attached Sheds picker on the Silo form, and the same decision as
  // parentForType above: narrow in SQL, before the page is cut, or the form
  // filters the first 50 rows in the browser and silently offers a subset.
  // A shed already fed by another silo is not on offer at all — that is the
  // "exactly one silo" rule showing up in the picker rather than only in the
  // refusal the save would have produced.
  @ApiProperty({
    description: 'Every active SHED location under this farm — the Attached Sheds picker on the Silo form. A shed may '
      + 'draw from several silos (D7), so nothing here is narrowed by what another silo already feeds.',
    required: false,
  })
  @IsOptional()
  @IsUUID()
  shedsForSilo?: string;

  @ApiProperty({ description: 'Only locations without a parent', required: false })
  @IsOptional()
  @Transform(({ value }) => value === 'true' ? true : value === 'false' ? false : value)
  @IsBoolean()
  rootOnly?: boolean;

  @ApiProperty({ description: 'Filter by active status', required: false })
  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  isActive?: boolean;

  @ApiProperty({ description: 'Search location code or name', required: false })
  @IsOptional()
  @IsString()
  search?: string;

}
